### ISSUE TITLE
点击Start Game没有反应

### ISSUE THREAD

**Issue by zhangchunsheng** [NetEase/treasures#12]
浪费时间啊

**Comment by laispace** [comment]
在跑 Treasure 这个 demo 的时候，会发现打开网页的 ”start game“ 按钮没反应，经排查发现是

web-server/public/js/main.js 中的 pomelo.request(‘area.playerHandler.getAnimation’ 没有执行。

解决办法是，在命令行中查询 pomelo 最新版本号：

$ pomelo —version

然后更新 game-server/package.json 中的 dependencies.pomelo 为最新版本，接着重新安装依赖：

$ sudo sh npm-install.sh

最后重启应用即可。

**Comment by jscMR** [comment]
thanks @laispace
