### ISSUE TITLE
gate负载均衡代码有错误，作者改完没有测试么？

### ISSUE THREAD

**Issue by dlutwuwei** [NetEase/treasures#13]
var crc = require('crc');

module.exports.dispatch = function(uid, connectors) {
    var index = Math.abs(crc.crc32(uid)) % connectors.length;
    return connectors[index];
};

crc.crc32(uid) 返回的是十六进制的字符串，应该写成parseInt(crc.crc32(uid),16)

**Comment by shuidong** [comment]
这教程做的实在太烂了。

**Comment by numbcoder** [comment]
@dlutwuwei @shuidong 

你们都跑过代码吗？先跑一下代码看看有没有问题再来喷行不行？
