### ISSUE TITLE
这个工程的pomelo版本太低，不能运行

### ISSUE THREAD

**Issue by cd0304** [NetEase/treasures#18]
在一个干净的环境，git clone这个工程下来后，发现客户端的消息跟gate和connector都能通信，但是客户端发消息到area服务器的时候就没响应了，后来发现是pomelo的版本太低了，升级到高版本的pomelo后，功能一切正常。

修改文件：game-server/package.json：
   pomelo的版本修改成如下，就可以了。
"pomelo": "~0.8.0"

**Comment by sjfkai** [comment]
just update `game-server/package.json`  `"pomelo": "~0.8.0"`
